[package]
name = "archive-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Extractr command-line interface"

[[bin]]
name = "extractr-cli"
path = "src/main.rs"

[dependencies]
archive-core = { workspace = true, features = ["rar"] }
clap = { version = "4", features = ["derive"] }
anyhow = { workspace = true }
tempfile = "3"
